server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/school_erp
spring.datasource.username=root
spring.datasource.password=managerr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
